tap "homebrew/bundle"

brew "fd"
brew "fish"
brew "jq"
brew "juliaup"
brew "mise"
brew "neovim"
brew "podman"
brew "ripgrep"
brew "rustup"
brew "tinymist"
brew "tokei"
brew "tree-sitter-cli"
brew "typst"
brew "wasm-tools"
brew "wasmtime"
brew "zola"

cask "anki"
cask "firefox"
cask "font-atkinson-hyperlegible"
cask "font-ibm-plex"
cask "font-juliamono"
cask "ghostty"
cask "iina"
cask "itsycal"        # Y-MM-dd EEEEE HH:mm
cask "libreoffice"
cask "mochi"          # (p)
cask "musescore"
cask "netnewswire"
cask "protonvpn"
cask "rectangle"
cask "spotify"        # (p)
cask "transmission"
cask "zotero"
