set mouse=a
set number
set relativenumber
set wildignorecase
set noshowmode
set confirm                "Ask to save stuff
set hidden                 "Hides buffers instead of closing them
set fileencoding=utf-8     "Encoding written to file

""" SPLIT WINDOWS
set splitright
set splitbelow

""" POSITION
set cursorline
set cursorcolumn
set colorcolumn=81

""" SEARCH
set ignorecase
set smartcase

""" WHITESPACE
set list
set listchars=tab:\|-,trail:*,extends:>,precedes:<,nbsp:_ "eol:~
set listchars+=space:· "not ASCII

""" INDENTATION
set smartindent
set expandtab    "<tab> inserts spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4

""" FOLDS
set foldmethod=indent
set foldlevel=2

""" SCROLLING
set nowrap
set scrolloff=20    "Keeps cursor centred
set sidescrolloff=20

""" VIM 8
if !has('nvim')
  syntax on
  set ruler
  "colorscheme desert
  set showcmd
  set autoread
  set wildmenu
  set hlsearch
  set incsearch
  set autoindent
  set laststatus=2
endif
