""" MAPPINGS

let mapleader = ' '
let maplocalleader = ','
noremap ; :
noremap \| ;

" Help
noremap <C-]> K

" Copy to system clipboard
noremap Y "+y

" Buffer navigation
noremap J }
noremap K {
noremap H ^
noremap L $

" Window navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l


""" OPTIONS

""" General
set mouse=a
set number
set relativenumber
set wildignorecase
set noshowmode
set confirm            " ask to save stuff
set hidden             " hides buffers instead of closing them
set fileencoding=utf-8 " encoding written to file
set spelllang=
set conceallevel=2

""" Persistent undo
set undofile
set undolevels=100  " How many undos
set undoreload=1000 " number of lines to save for undo

""" LSP-related
set completeopt=menuone,noinsert,noselect
set shortmess+=c
set signcolumn=number
set updatetime=300

""" Split windows
set splitbelow
set splitright

""" Position
set cursorcolumn
set cursorline
set colorcolumn=81

""" Search
set ignorecase
set smartcase

""" Whitespace
set list
set listchars=tab:\|-,trail:*,extends:>,precedes:<,nbsp:_,eol:~
set listchars+=space:· "not ASCII

""" Indentation
set expandtab     "<tab> inserts spaces
set smartindent
set shiftwidth=4
set softtabstop=4
set tabstop=4

""" Folds
set foldlevel=2
set foldmethod=indent

""" Scrolling
set nowrap
set scrolloff=5
set sidescrolloff=5

""" Vim 8
if !has('nvim')
    syntax enable
    set ruler
    set showcmd
    set autoread
    set wildmenu
    set hlsearch
    set incsearch
    set autoindent
    set laststatus=2
endif

" Netrw
let g:netrw_banner = 0     " no banner
let g:netrw_liststyle = 3  " tree style listing
let g:netrw_dirhistmax = 0 " no netrw history
