[colors]
foreground    = "#5C4D3D"
background    = "#E8D9C9"
cursor_bg     = "#5C4D3D"
cursor_border = "#5C4D3D"
cursor_fg     = "#5C4D3D"
selection_bg  = "#E0CCB8"
selection_fg  = "#5C4D3D"

ansi = ["#E8D9C9","#C43149","#6AAB49","#D79B23","#6D7EB0","#7A569F","#629393","#8A735C"] 
brights = ["#D1B394","#E0593E","#6AAB49","#CA731C","#6D7EB0","#BC62AD","#3D8F66","#5C4D3D"] 
